### PR TITLE
Open Source project updates

### PR DESCRIPTION
**Pull request by postalservice14**
@videlalvaro Let me know if I've taken this too far. :-)

I wanted to get this project to follow some more of the open source package conventions.  Much of this was based on the PHP League's skeleton project (https://github.com/thephpleague/skeleton).  In doing so I've added the following:

* Scrutinizer (You'll need to create a scrutinizer-ci.com account if you don't already have one)
* Added a CONTRIBUTING.md
* Updated the travis.yml file
* Updated the README.md file to include some new "badges"

Let me know if there is anything here you don't agree with...

### CODE REVIEW

**Comment by videlalvaro** [comment]
From a quick look this looks great, thanks. I'll try to merge it next week.

**Comment by videlalvaro** [comment]
I've created the scrutinizer account. What do I do there now?

**Comment by postalservice14** [comment]
Perfect.  If you linked the scrutinizer account to your github account.

1. Merge in these changes so the scrutinizer.yml file exists
2. You should be able to add the php-amqplib project to the scrutinizer projects list.  Once that is done it will run the first build and show you results when it's finished.

**Comment by postalservice14** [comment]
:+1: Awesome, thanks!  Looks great!

**Comment by videlalvaro** [comment]
thank you for this

**Pull request merged**
