### PR TITLE
Update demo config

### PR DESCRIPTION
**Pull request by sergeyklay**

### CODE REVIEW

**Comment by videlalvaro** [comment]
why do we need this change? If you get the source from github and then run `composer install` everything works as expected

**Comment by sergeyklay** [comment]
I proposed these changes, because only in this way it is possible to use these examples.

**Comment by videlalvaro** [comment]
If you clone the library directly from the Github repo, then run composer install, the examples work perfectly. They might not work if `php-amqplib` is a dependency of one of your repos or something like that. The path you provide in the changes suggest you have a different directory structure. I have something like:

/PhpAmqpLib
/demo
/vendor

**Comment by sergeyklay** [comment]
Thank you for the explanation

**Pull request closed without merging**
